INSERT INTO APPOINTMENT (ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES (1, 'John', 'Peterson', '29292929');
INSERT INTO APPOINTMENT (ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES (2, 'Peter', 'Patrick', '26253327');
INSERT INTO APPOINTMENT (ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES (3, 'Sarah', 'Smith', '25293761');
INSERT INTO APPOINTMENT (ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES (4, 'Alexandra', 'Williams', '22297698');
INSERT INTO APPOINTMENT (ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES (5, 'Jane', 'Peterson', '29267430');
