INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('John', 'Peterson', '29292929');
INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('Peter', 'Patrick', '26253327');
INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('Sarah', 'Smith', '25293761');
INSERT INTO APPOINTMENT (FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('Alexandra', 'Williams', '22297698');